### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by NidalChateur** [AlexandreGazagnes/awdible#4] opened 2024-02-12 22:37 UTC
## General

- **Operating System**: Windows 11
- **Python version**: 3.10.11
- **awdible version**: 0.2.3

## Acknowledgement

- [ ] I read the [documentation page](https://alexandregazagnes.github.io/awdible/)
      before writing a new bug report

## Bug description

Tests have to be updated

### Context

git badge status : failing

### Expected behavior

git badge status : passing

_Write here the expected behavior_

### Observed behavior

_Write here the observed behavior_

### Code to reproduce the bug

_Write here the code to reproduce the bug_

```python
# Your code here
```

### Error message

_Write here the error message_
```bash
# Your error message here
```

## Minimal but working code sample to ease bug fix for `awdible` team

_Write here the minimal code sample to ease bug fix for `awdible` team_

**Comment by AlexandreGazagnes** [comment] 2024-02-13 11:57
Hi Nidal, 

Could you please have a look to 0.2.4 tests status? 
I think the problem is solved but a confirmation could be a nice thing.

**Comment by AlexandreGazagnes** [comment] 2024-02-17 02:08
Hi @NidalChateur 

I'm closing this issue due to #10.
Please consider about discuessing on the #10 

I will be happy to have some help

**Closed by AlexandreGazagnes** 2024-02-17 02:08 UTC
Labels: bug, duplicate, help wanted, urgent, testing
